name: CI

on: [push]

env:
  CI: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    uses: inrupt/typescript-sdk-tools/.github/workflows/reusable-lint.yml@v3.2.1

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x", "18.x"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - name: Archive code coverage results
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage

  sonar-scan:
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Sonar analysis needs the full history for features like automatic assignment of bugs. If the following step
          # is not included the project will show a warning about incomplete information.
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/
      - uses: SonarSource/sonarcloud-github-action@v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
